#Requires -Version 5.1
<#
.SYNOPSIS
    RARLab WinRAR 7.13 Deployment Script

.DESCRIPTION
    PSADT v4 deployment script for WinRAR
    Installer Type: exe
    Template Complexity: standard

    Generated by Packager-MCP
    Generated: 2025-12-12T22:41:39.511Z

.PARAMETER DeploymentType
    The type of deployment to perform. Options: Install, Uninstall

.PARAMETER DeployMode
    The deployment mode. Options: Interactive, Silent, NonInteractive

.PARAMETER AllowRebootPassThru
    Allows the 3010 return code (restart required) to be passed back

.PARAMETER TerminalServerMode
    Changes to terminal server compatible mode

.PARAMETER DisableLogging
    Disables logging to file

.NOTES
    Application: WinRAR
    Version: 7.13
    Vendor: RARLab

.LINK
    https://psappdeploytoolkit.com
#>

[CmdletBinding()]
param (
    [ValidateSet('Install', 'Uninstall')]
    [string]$DeploymentType = 'Install',

    [ValidateSet('Interactive', 'Silent', 'NonInteractive')]
    [string]$DeployMode = 'Interactive',

    [switch]$AllowRebootPassThru,

    [switch]$TerminalServerMode,

    [switch]$DisableLogging
)

#region Session Configuration
$adtSession = @{
    AppVendor = 'RARLab'
    AppName = 'WinRAR'
    AppVersion = '7.13'
    AppArch = 'x64'
    AppLang = 'EN'
    AppRevision = '01'
    AppSuccessExitCodes = @(0)
    AppRebootExitCodes = @(1641, 3010)
    AppProcessesToClose = @()
    AppScriptVersion = '1.0.0'
    AppScriptDate = ''
    AppScriptAuthor = 'IT Admin'
    RequireAdmin = $true
    DeployAppScriptFriendlyName = $MyInvocation.MyCommand.Name
    DeployAppScriptParameters = $PSBoundParameters
    DeployAppScriptVersion = '4.1.7'
}
#endregion

#region Initialization
$ErrorActionPreference = [System.Management.Automation.ActionPreference]::Stop
$ProgressPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue
Set-StrictMode -Version 1

try {
    Import-Module -FullyQualifiedName @{ ModuleName = "$PSScriptRoot\PSAppDeployToolkit\PSAppDeployToolkit.psd1"; Guid = '8c3c366b-8606-4576-9f2d-4051144f7ca2'; ModuleVersion = '4.1.7' } -Force
    $iadtParams = Get-ADTBoundParametersAndDefaultValues -Invocation $MyInvocation
    $adtSession = Remove-ADTHashtableNullOrEmptyValues -Hashtable $adtSession
    $adtSession = Open-ADTSession @adtSession @iadtParams -PassThru
}
catch {
    $Host.UI.WriteErrorLine((Out-String -InputObject $_ -Width ([System.Int32]::MaxValue)))
    exit 60008
}
#endregion

#region Variables
# Installer Configuration
$InstallerFile = 'winrar-x64-713.exe'
$SilentArgs = '/s'
$UninstallArgs = '/s'
#endregion

#region Deployment Functions
function Install-ADTDeployment {
    [CmdletBinding()]
    param()

    # Pre-Install
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"
    Write-ADTLogEntry -Message "=== Pre-Installation Phase ==="

    $saiwParams = @{
        AllowDeferCloseProcesses = $true
        DeferTimes = 3
        CheckDiskSpace = $true
        PersistPrompt = $true
        BlockExecution = $true
    }
    if ($adtSession.AppProcessesToClose.Count -gt 0) {
        $saiwParams.Add('CloseProcesses', $adtSession.AppProcessesToClose)
        $saiwParams.Add('CloseProcessesCountdown', 300)
    }
    Show-ADTInstallationWelcome @saiwParams

    # Check for existing installation
    $existingApp = Get-ADTApplication -Name 'WinRAR'
    if ($existingApp) {
        Write-ADTLogEntry -Message "Found existing installation: $($existingApp.DisplayName) v$($existingApp.DisplayVersion)"
        # CUSTOMIZE: Decide whether to upgrade or skip
    }


    Show-ADTInstallationProgress -StatusMessage 'Installing WinRAR...'

    # Install
    $adtSession.InstallPhase = $adtSession.DeploymentType
    Write-ADTLogEntry -Message "=== Installation Phase ==="

    $installerPath = Join-Path -Path $adtSession.DirFiles -ChildPath $InstallerFile

    # Execute installer with appropriate arguments
    # CUSTOMIZE: Adjust based on installer type (Inno Setup, NSIS, InstallShield, etc.)
    $result = Start-ADTProcess -FilePath $installerPath -ArgumentList $SilentArgs -PassThru

    # Handle common exit codes
    switch ($result.ExitCode) {
        0 { Write-ADTLogEntry -Message "Installation successful" }
        3010 { Write-ADTLogEntry -Message "Installation successful - restart required" -Severity 2 }
        1641 { Write-ADTLogEntry -Message "Installation successful - restart initiated" -Severity 2 }
        default {
            if ($result.ExitCode -ne 0) {
                Write-ADTLogEntry -Message "Installer returned exit code: $($result.ExitCode)" -Severity 2
            }
        }
    }

    # Post-Install
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"
    Write-ADTLogEntry -Message "=== Post-Installation Phase ==="

    # Verify installation
    Start-Sleep -Seconds 2  # Brief pause for registry to update
    $installed = Get-ADTApplication -Name 'WinRAR'
    if (-not $installed) {
        Write-ADTLogEntry -Message "Warning: Application not found in registry after installation" -Severity 2
    } else {
        Write-ADTLogEntry -Message "Verified installation: $($installed.DisplayName) v$($installed.DisplayVersion)"
    }

    # CUSTOMIZE: Add post-installation configuration
    # $configSource = Join-Path -Path $adtSession.DirFiles -ChildPath 'config.xml'
    # Copy-ADTFile -Path $configSource -Destination "$env:ProgramData\App\config.xml"

}

function Uninstall-ADTDeployment {
    [CmdletBinding()]
    param()

    # Pre-Uninstall
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"
    Write-ADTLogEntry -Message "=== Pre-Uninstallation Phase ==="

    if ($adtSession.AppProcessesToClose.Count -gt 0) {
        Show-ADTInstallationWelcome -CloseProcesses $adtSession.AppProcessesToClose -CloseProcessesCountdown 60
    }
    Show-ADTInstallationProgress -StatusMessage 'Uninstalling WinRAR...'

    # Uninstall
    $adtSession.InstallPhase = $adtSession.DeploymentType
    Write-ADTLogEntry -Message "=== Uninstallation Phase ==="

    $app = Get-ADTApplication -Name 'WinRAR'

    if ($app -and $app.UninstallString) {
        # Parse uninstall string
        $uninstallCmd = $app.UninstallString
        Write-ADTLogEntry -Message "Uninstall command: $uninstallCmd"

        # Extract path (handle quoted paths)
        if ($uninstallCmd -match '^"([^"]+)"(.*)$') {
            $uninstallPath = $Matches[1]
        } elseif ($uninstallCmd -match '^(\S+)(.*)$') {
            $uninstallPath = $Matches[1]
        } else {
            $uninstallPath = $uninstallCmd
        }

        if (Test-Path $uninstallPath) {
            Start-ADTProcess -FilePath $uninstallPath -ArgumentList $UninstallArgs
        } else {
            Write-ADTLogEntry -Message "Uninstaller not found at: $uninstallPath" -Severity 2
        }
    } else {
        Write-ADTLogEntry -Message "Application not found or no uninstall string available" -Severity 2
    }

    # Post-Uninstall
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"
    Write-ADTLogEntry -Message "=== Post-Uninstallation Phase ==="

    # CUSTOMIZE: Clean up remaining files and registry
    # Remove-ADTFolder -Path "$env:ProgramFiles\Vendor\App" -ContinueOnError
}

function Repair-ADTDeployment {
    [CmdletBinding()]
    param()

    # Pre-Repair
    $adtSession.InstallPhase = "Pre-$($adtSession.DeploymentType)"
    Write-ADTLogEntry -Message "=== Repair Phase ==="

    if ($adtSession.AppProcessesToClose.Count -gt 0) {
        Show-ADTInstallationWelcome -CloseProcesses $adtSession.AppProcessesToClose -CloseProcessesCountdown 60
    }
    Show-ADTInstallationProgress -StatusMessage 'Repairing WinRAR...'

    # Repair
    $adtSession.InstallPhase = $adtSession.DeploymentType

    # For most EXE installers, repair means reinstall
    Write-ADTLogEntry -Message "Performing repair by reinstalling"

    # Uninstall first
    $app = Get-ADTApplication -Name 'WinRAR'
    if ($app.UninstallString) {
        $uninstallPath = ($app.UninstallString -split ' ')[0] -replace '"', ''
        if (Test-Path $uninstallPath) {
            Start-ADTProcess -FilePath $uninstallPath -ArgumentList $UninstallArgs
            Start-Sleep -Seconds 5
        }
    }

    # Reinstall
    $installerPath = Join-Path -Path $adtSession.DirFiles -ChildPath $InstallerFile
    Start-ADTProcess -FilePath $installerPath -ArgumentList $SilentArgs

    # Post-Repair
    $adtSession.InstallPhase = "Post-$($adtSession.DeploymentType)"
    Write-ADTLogEntry -Message "Repair completed"
}
#endregion

#region Invocation
try {
    & "$($adtSession.DeploymentType)-ADTDeployment"
    Close-ADTSession
}
catch {
    Write-ADTLogEntry -Message "Unhandled error: $(Resolve-ADTErrorRecord -ErrorRecord $_)" -Severity 3
    Close-ADTSession -ExitCode 60001
}
