#Requires -Version 5.1
<#
.SYNOPSIS
    RARLab WinRAR 7.13.0 Deployment Script

.DESCRIPTION
    PSADT v4 deployment script for WinRAR
    Installer Type: exe
    Template Complexity: standard

    Generated by Packager-MCP
    Generated: 2025-12-12T00:36:52.153Z

.PARAMETER DeploymentType
    The type of deployment to perform. Options: Install, Uninstall

.PARAMETER DeployMode
    The deployment mode. Options: Interactive, Silent, NonInteractive

.PARAMETER AllowRebootPassThru
    Allows the 3010 return code (restart required) to be passed back

.PARAMETER TerminalServerMode
    Changes to terminal server compatible mode

.PARAMETER DisableLogging
    Disables logging to file

.NOTES
    Application: WinRAR
    Version: 7.13.0
    Vendor: RARLab

.LINK
    https://psappdeploytoolkit.com
#>

[CmdletBinding()]
param (
    [ValidateSet('Install', 'Uninstall')]
    [string]$DeploymentType = 'Install',

    [ValidateSet('Interactive', 'Silent', 'NonInteractive')]
    [string]$DeployMode = 'Interactive',

    [switch]$AllowRebootPassThru,

    [switch]$TerminalServerMode,

    [switch]$DisableLogging
)

#region Import Module and Initialize
try {
    # Import PSADT module
    Import-Module "$PSScriptRoot\PSAppDeployToolkit" -Force -ErrorAction Stop
}
catch {
    Write-Error "Failed to import PSAppDeployToolkit module: $($_.Exception.Message)"
    exit 60001
}

# Initialize deployment session
$adtParams = @{
    InstallName         = 'WinRAR'
    InstallVersion      = '7.13.0'
    Publisher           = 'RARLab'
    DeploymentType      = $DeploymentType
    DeployMode          = $DeployMode
    AllowRebootPassThru = $AllowRebootPassThru
    TerminalServerMode  = $TerminalServerMode
    DisableLogging      = $DisableLogging
}

try {
    Initialize-ADTDeployment @adtParams
}
catch {
    Write-Error "Failed to initialize deployment: $($_.Exception.Message)"
    exit 60001
}
#endregion

#region Variables
# Installer Configuration
$InstallerFile = 'winrar-x64-713.exe'
$SilentArgs = '/S'
$UninstallArgs = '/S'

# Applications to close
$AppsToClose = 'WinRAR,Rar,UnRAR'
#endregion

#region Main Deployment Logic
try {
    switch ($DeploymentType) {
        'Install' {
            #region Pre-Installation
            Write-ADTLogEntry -Message "=== Pre-Installation Phase ==="

            if ($AppsToClose) {
                Show-ADTInstallationWelcome -CloseApps $AppsToClose `
                    -CloseAppsCountdown 300 `
                    -PersistPrompt `
                    -BlockExecution
            }

            # Check for existing installation
            $existingApp = Get-ADTInstalledApplication -Name 'WinRAR'
            if ($existingApp) {
                Write-ADTLogEntry -Message "Found existing installation: $($existingApp.DisplayName) v$($existingApp.DisplayVersion)"

                # CUSTOMIZE: Decide whether to upgrade or skip
                # Option 1: Remove old version first
                # Option 2: Let installer handle upgrade
                # Option 3: Skip if same version
            }


            Show-ADTInstallationProgress -StatusMessage 'Installing WinRAR...'
            #endregion

            #region Installation
            Write-ADTLogEntry -Message "=== Installation Phase ==="

            $installerPath = Join-Path -Path $ADTSession.FilesDirectory -ChildPath $InstallerFile

            # Execute installer with appropriate arguments
            # CUSTOMIZE: Adjust based on installer type (Inno Setup, NSIS, InstallShield, etc.)
            $result = Start-ADTProcess -FilePath $installerPath `
                -Arguments $SilentArgs `
                -PassThru

            # Handle common exit codes
            switch ($result.ExitCode) {
                0 { Write-ADTLogEntry -Message "Installation successful" }
                3010 {
                    Write-ADTLogEntry -Message "Installation successful - restart required" -Severity 2
                }
                1641 {
                    Write-ADTLogEntry -Message "Installation successful - restart initiated" -Severity 2
                }
                default {
                    if ($result.ExitCode -ne 0) {
                        Write-ADTLogEntry -Message "Installer returned exit code: $($result.ExitCode)" -Severity 2
                    }
                }
            }
            #endregion

            #region Post-Installation
            Write-ADTLogEntry -Message "=== Post-Installation Phase ==="

            # Verify installation
            Start-Sleep -Seconds 2  # Brief pause for registry to update
            $installed = Get-ADTInstalledApplication -Name 'WinRAR'
            if (-not $installed) {
                Write-ADTLogEntry -Message "Warning: Application not found in registry after installation" -Severity 2
                # CUSTOMIZE: Add file-based verification if needed
                # if (-not (Test-Path "$env:ProgramFiles\Vendor\App\app.exe")) {
                #     throw "Installation verification failed"
                # }
            } else {
                Write-ADTLogEntry -Message "Verified installation: $($installed.DisplayName) v$($installed.DisplayVersion)"
            }

            # CUSTOMIZE: Add post-installation configuration
            # $configSource = Join-Path -Path $ADTSession.FilesDirectory -ChildPath 'config.xml'
            # Copy-ADTFile -Path $configSource -Destination "$env:ProgramData\App\config.xml"
            # Set-ADTRegistryKey -Key 'HKLM:\SOFTWARE\App' -Name 'Setting' -Value 'Value'

            #endregion
        }

        'Uninstall' {
            #region Pre-Uninstallation
            Write-ADTLogEntry -Message "=== Pre-Uninstallation Phase ==="

            if ($AppsToClose) {
                Show-ADTInstallationWelcome -CloseApps $AppsToClose -CloseAppsCountdown 60
            }

            Show-ADTInstallationProgress -StatusMessage 'Uninstalling WinRAR...'
            #endregion

            #region Uninstallation
            Write-ADTLogEntry -Message "=== Uninstallation Phase ==="

            $app = Get-ADTInstalledApplication -Name 'WinRAR'

            if ($app -and $app.UninstallString) {
                # Parse uninstall string
                $uninstallCmd = $app.UninstallString
                Write-ADTLogEntry -Message "Uninstall command: $uninstallCmd"

                # Extract path (handle quoted paths)
                if ($uninstallCmd -match '^"([^"]+)"(.*)$') {
                    $uninstallPath = $Matches[1]
                    $existingArgs = $Matches[2].Trim()
                } elseif ($uninstallCmd -match '^(\S+)(.*)$') {
                    $uninstallPath = $Matches[1]
                    $existingArgs = $Matches[2].Trim()
                } else {
                    $uninstallPath = $uninstallCmd
                    $existingArgs = ''
                }

                if (Test-Path $uninstallPath) {
                    # Use silent uninstall arguments
                    Start-ADTProcess -FilePath $uninstallPath -Arguments $UninstallArgs
                } else {
                    Write-ADTLogEntry -Message "Uninstaller not found at: $uninstallPath" -Severity 2
                }
            } else {
                Write-ADTLogEntry -Message "Application not found or no uninstall string available" -Severity 2
            }
            #endregion

            #region Post-Uninstallation
            Write-ADTLogEntry -Message "=== Post-Uninstallation Phase ==="

            # CUSTOMIZE: Clean up remaining files and registry
            # Remove-ADTFolder -Path "$env:ProgramFiles\Vendor\App" -ContinueOnError
            # Remove-ADTFolder -Path "$env:ProgramData\Vendor\App" -ContinueOnError
            # Remove-ADTRegistryKey -Key 'HKLM:\SOFTWARE\Vendor\App' -Recurse -ContinueOnError
            #endregion
        }
    }

    Complete-ADTDeployment -DeploymentStatus 'Complete'
}
catch {
    Write-ADTLogEntry -Message "Deployment failed: $($_.Exception.Message)" -Severity 3
    Write-ADTLogEntry -Message "Stack trace: $($_.ScriptStackTrace)" -Severity 3

    try {
        Complete-ADTDeployment -DeploymentStatus 'Failed' -ErrorMessage $_.Exception.Message
    }
    catch {
        Write-Error "Failed to complete deployment: $($_.Exception.Message)"
        exit 60008
    }
}
