function Export-PackagerMcpConfig {
  <#
    .SYNOPSIS
    Exports Packager-MCP configuration to a YAML file.

    .DESCRIPTION
    Creates or updates the intune_mcp_config.yaml file with the Azure AD
    application configuration needed for the MCP server.

    .PARAMETER TenantId
    The Azure AD tenant ID.

    .PARAMETER ClientId
    The application (client) ID.

    .PARAMETER CertificatePath
    Path to the PEM certificate file (used by @azure/identity).

    .PARAMETER CertificateThumbprint
    The certificate thumbprint.

    .PARAMETER OutputPath
    Path for the YAML config file. Default: './intune_mcp_config.yaml'

    .EXAMPLE
    Export-PackagerMcpConfig -TenantId $tenantId -ClientId $clientId `
      -CertificatePath './packager-mcp.pfx' -CertificateThumbprint $thumbprint
  #>
  [CmdletBinding()]
  param(
    [Parameter(Mandatory)]
    [string]$TenantId,

    [Parameter(Mandatory)]
    [string]$ClientId,

    [Parameter(Mandatory)]
    [string]$CertificatePath,

    [Parameter(Mandatory)]
    [string]$CertificateThumbprint,

    [string]$OutputPath = './intune_mcp_config.yaml'
  )

  $fullCertPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($CertificatePath)
  $fullOutputPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputPath)

  Write-Host "Writing configuration to: $fullOutputPath" -ForegroundColor Cyan

  # Build YAML content manually to avoid powershell-yaml dependency
  $yaml = @"
# Packager-MCP Intune Configuration
# Generated by Setup-PackagerMcpIntune.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
#
# This file contains the Azure AD application credentials for the Packager-MCP
# server to authenticate with Microsoft Intune via the Graph API.
#
# SECURITY WARNING: This file references a certificate that grants access to
# your Intune environment. Protect both this file and the certificate file.

azure:
  # Azure AD tenant ID (directory ID)
  tenantId: "$TenantId"

  # Application (client) ID from the app registration
  clientId: "$ClientId"

  # Authentication method: certificate
  authMethod: "certificate"

  # Path to the PEM certificate file (required by @azure/identity v4.x)
  certificatePath: "$($fullCertPath -replace '\\', '/')"

  # Certificate thumbprint (for validation)
  certificateThumbprint: "$CertificateThumbprint"

# Optional: Override specific settings
# intune:
#   # Default app category name (must exist in your tenant)
#   defaultCategory: "Productivity"
#
#   # Default architecture
#   defaultArchitecture: "x64"
#
#   # Minimum OS version
#   minimumOsVersion: "10.0.14393.0"
"@

  try {
    Set-Content -LiteralPath $fullOutputPath -Value $yaml -Encoding UTF8 -Force
    Write-Host 'Configuration saved successfully.' -ForegroundColor Green
    Write-PackagerMcpLog "Configuration saved to: $fullOutputPath" 'INFO'
  }
  catch {
    throw "Failed to write configuration file: $($_.Exception.Message)"
  }

  return $fullOutputPath
}
