/**
 * Intune MCP Configuration Types
 *
 * Types for the intune_mcp_config.yaml configuration file generated by
 * Setup-PackagerMcpIntune.ps1.
 */

/**
 * Azure AD authentication configuration
 */
export interface AzureConfig {
  /** Azure AD tenant ID (directory ID) */
  tenantId: string;

  /** Application (client) ID from the app registration */
  clientId: string;

  /** Authentication method - currently only 'certificate' is supported */
  authMethod: 'certificate';

  /** Path to the PFX certificate file (relative or absolute) */
  certificatePath: string;

  /** Certificate thumbprint for validation */
  certificateThumbprint: string;
}

/**
 * Optional Intune-specific configuration overrides
 */
export interface IntuneConfig {
  /** Default app category name (must exist in tenant) */
  defaultCategory?: string;

  /** Default architecture for apps */
  defaultArchitecture?: 'x86' | 'x64' | 'arm' | 'arm64';

  /** Minimum OS version requirement */
  minimumOsVersion?: string;
}

/**
 * Complete configuration file structure
 */
export interface IntuneMcpConfig {
  /** Azure AD configuration */
  azure: AzureConfig;

  /** Optional Intune-specific settings */
  intune?: IntuneConfig;
}

/**
 * Configuration source priority (highest to lowest):
 * 1. Environment variables (AZURE_TENANT_ID, AZURE_CLIENT_ID, etc.)
 * 2. YAML config file (via INTUNE_MCP_CONFIG env var)
 * 3. Default YAML locations (./intune_mcp_config.yaml, ~/.packager-mcp/config.yaml)
 */
export type ConfigSource = 'environment' | 'yaml' | 'default';

/**
 * Result of loading configuration
 */
export interface ConfigLoadResult {
  /** The loaded configuration */
  config: IntuneMcpConfig;

  /** Where the configuration was loaded from */
  source: ConfigSource;

  /** Path to the config file (if loaded from file) */
  configPath?: string;
}
